---
abstract: 'build simple recursive-descent parsers'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Parser-MGC
provides:
  Parser::MGC:
    file: lib/Parser/MGC.pm
    version: 0.02
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
