---
abstract: 'build simple recursive-descent parsers'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  File::Temp: 0
  Test::More: 0.88
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Parser-MGC
provides:
  Parser::MGC:
    file: lib/Parser/MGC.pm
    version: 0.12
requires:
  File::Slurp: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.12
